- name: Install
  apt: pkg="php5.6-dev" state=present
#  when: php.pecl_packages is defined

#- name: Install Package
 # apt:
 #   pkg={{ item }}
 #   state=present
 #   update_cache=yes
 #   cache_valid_time=3600
 # with_items:
  #  - php-bz2
  #  - phar
 # become: true

#- name: Install Package
#  shell: echo "\n\n\n\n\n\n\n\n\n" | pecl install {{ item }}
#  register: pecl_result
#  changed_when: "'already installed' not in pecl_result.stdout"
#  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
#  with_items: 
#    - bz2
#    - phar

#- name: Create extension .ini file
# template: >
#    src="extension.tpl"
#    dest="/etc/php/5.6/mods-available/{{ item }}.ini"
#    owner="root"
#    group="root"
#    mode=0644
#  with_items: 
#    - phar
#  when: php.pecl_packages is defined

#- name: Enable extension
#  shell: php5enmod {{ item }}
#  with_items:
#    - phar
#  when: php.pecl_packages is defined
